Remove translated occurrences of "preferred_network_mode_choices"
The string-array "preferred_network_mode_choices" is now untranslatable, but
there are still almost all the old translations of it.
Old translated occurrences of "preferred_network_mode_choices" have less items
than the expected ones (according to what is defined inside values/strings.xml).

These occurrences are causing "com.android.phone" process force closes because
of ArrayIndexOutOfBoundsException during the bind of the preference view:

  Process: com.android.phone, PID: 13517
  java.lang.ArrayIndexOutOfBoundsException: length=13; index=22
      at android.preference.ListPreference.getEntry(ListPreference.java:219)
      at android.preference.ListPreference.getSummary(ListPreference.java:164)
      at android.preference.Preference.onBindView(Preference.java:550)
      at android.preference.Preference.getView(Preference.java:489)
      at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
  ...
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
  Force finishing activity com.android.phone/.MobileNetworkSettings

Change-Id: Ic5e1916652b5c59fb2aff0a50e7257889d6982f2